## Configuration file for a Bayes-Yule experiment

# Setup for the model
model:
  name: Yule # "Yule" or "BirthDeath"
  config:
    n_init: 1
    Nact: 1000
    Ninact: 1000
    max_pop: 500000

# Ground truth for scoring and generation
params:
  LDA: 0.3
  lda: 0.012
  gamma: 0.001
  mu: 0.0033

# Set up for the inference backend
inference:
  name: SBI # "SBI"
  config:
    method : NPE
    num_simulations : 100
    num_rounds : 3
    random_seed : 42
    num_samples : 10
    num_workers : 10
    device : cpu