## Configuration file for a Bayes-Yule experiment

# Setup for the generator
generator:
  name: BirthDeathAbundance # "YuleAbundance" or "BirthDeathAbundance"
  config:
    n_init: 1
    Nact: 1000
    Ninact: 1000
    max_pop: 100000

# Summary statistics that will be given as input to the inference
stats: 
  name: "Abundance"
  config:
    additional_stats: True

# Prior distribution for the parameters
prior:
  # TODO : Pouvoir faire en sorte que n'importe quel distribution déjà existante dans Pytorch puisse être renseigné ici
  name: "ConstrainedUniform3D"
  config:
    low: [0.0, 0.0, 0.0]
    high: [1, 0.03, 0.02]

# Ground truth for scoring and generation
params:
  LDA: 0.5
  lda: 0.009
  mu: 0.0033

# Set up for the inference backend
inference:
  name: SBI # "SBI"
  config:
    method : NPE
    num_simulations : 5000
    num_rounds : 1
    random_seed : 42
    num_samples : 500
    num_workers : 10
    device : cpu  