## Configuration file for a Bayes-Yule experiment

# Setup for the generator
generator:
  name: YuleAbundance # "YuleAbundance" or "BirthDeathAbundance"
  config:
    n_init: 1
    Nact: 1000
    Ninact: 1000
    max_pop: 2000000

# Summary statistics that will be given as input to the inference
stats: 
  name: "Abundance"
  config:
    additional_stats: True

# Prior distribution for the parameters
prior:
  # TODO : Pouvoir faire en sorte que n'importe quel distribution déjà existante dans Pytorch puisse être renseigné ici
  name: "ConstrainedUniform4D"
  config:
    low: [0.0, 0.0, 0.0, 0.0]
    high: [1.0, 0.03, 0.02, 0.02]

# Set up for the inference backend
inference:
  name: SBI # "SBI"
  config:
    posterior_path: "posteriors/yule/posterior.pkl"
    num_samples : 500

